### ISSUE TITLE
gemm_op not defined

### ISSUE THREAD

**Issue by bigbigda** [AngusG/tensorflow-xnor-bnn#4]
I clone this project and do the orders in readme.md, but I always encounter the error belows when I run 
```python test_gemm_op.py```, I have changed my tensorflow to 1.2.1, but it's still there.

In my opinion, the Makefile generate a C dynamic library, then how can the module be directly loaded. And I have tried to load the gemm_op.so in the dll manner, but I was informed that some label can't be found.

Is there anyone else encounter the same problem?  this have puzzled me one whole day. 

```
Traceback (most recent call last):
  File "test_gemm_op.py", line 2, in <module>
    from gemm_op import xnor_gemm
ImportError: dynamic module does not define module export function (PyInit_gemm_op)
```

**Comment by bigbigda** [comment]
As a supplyment, I reference the guides in [https://www.tensorflow.org/extend/adding_an_op#gpu_support](https://www.tensorflow.org/extend/adding_an_op#gpu_support), I find the guide use `tf.load_op_library` to load the .so library.

**Comment by AngusG** [comment]
Sorry about this. I renamed `gemm_op.py` to `tf_gemm_op.py` and forgot to update the test. Please replace `from gemm_op` with `from tf_gemm_op` and it should work.

**Comment by mohendra** [comment]
gemm_op.so not found
